// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAV0gawAWIe3-D1eq_xFH06bwIjraNxF88',
    appId: '1:437548364812:web:a54392a33c7a14411aaa29',
    messagingSenderId: '437548364812',
    projectId: 'sajilokhata-102c9',
    authDomain: 'sajilokhata-102c9.firebaseapp.com',
    storageBucket: 'sajilokhata-102c9.firebasestorage.app',
    measurementId: 'G-VBYRMB78ZE',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBhmMPyL8XFKaXCsFO_jL4KwRZYsndh8Xo',
    appId: '1:437548364812:android:f568ccf76647f7371aaa29',
    messagingSenderId: '437548364812',
    projectId: 'sajilokhata-102c9',
    storageBucket: 'sajilokhata-102c9.firebasestorage.app',
  );
  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCOzHZb0nDsb5vNLng0cqdwhGaeC9E8F_w',
    appId: '1:437548364812:ios:8aca3e46bd6a0b831aaa29',
    messagingSenderId: '437548364812',
    projectId: 'sajilokhata-102c9',
    storageBucket: 'sajilokhata-102c9.firebasestorage.app',
    androidClientId:
        '437548364812-4dkdkc5gvs05hlnrrc6sqt336r097uot.apps.googleusercontent.com',
    iosClientId:
        '437548364812-g3rb0s23d25khv0mmp7ueniaro5ac6h7.apps.googleusercontent.com',
    iosBundleId: 'com.zaddyai.sajilokhata',
  );
  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCOzHZb0nDsb5vNLng0cqdwhGaeC9E8F_w',
    appId: '1:437548364812:ios:8aca3e46bd6a0b831aaa29',
    messagingSenderId: '437548364812',
    projectId: 'sajilokhata-102c9',
    storageBucket: 'sajilokhata-102c9.firebasestorage.app',
    androidClientId:
        '437548364812-4dkdkc5gvs05hlnrrc6sqt336r097uot.apps.googleusercontent.com',
    iosClientId:
        '437548364812-g3rb0s23d25khv0mmp7ueniaro5ac6h7.apps.googleusercontent.com',
    iosBundleId: 'com.zaddyai.sajilokhata',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAV0gawAWIe3-D1eq_xFH06bwIjraNxF88',
    appId: '1:437548364812:web:2175f2208e68680d1aaa29',
    messagingSenderId: '437548364812',
    projectId: 'sajilokhata-102c9',
    authDomain: 'sajilokhata-102c9.firebaseapp.com',
    storageBucket: 'sajilokhata-102c9.firebasestorage.app',
    measurementId: 'G-6GD8SN976T',
  );
}
