// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAV0gawAWIe3-D1eq_xFH06bwIjraNxF88',
    appId: '1:437548364812:web:5315449e1d0cd7551aaa29',
    messagingSenderId: '437548364812',
    projectId: 'sajilokhata-102c9',
    authDomain: 'sajilokhata-102c9.firebaseapp.com',
    storageBucket: 'sajilokhata-102c9.firebasestorage.app',
    measurementId: 'G-DX1S16PVHD',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBhmMPyL8XFKaXCsFO_jL4KwRZYsndh8Xo',
    appId: '1:437548364812:android:4b0b8b29c63b06e31aaa29',
    messagingSenderId: '437548364812',
    projectId: 'sajilokhata-102c9',
    storageBucket: 'sajilokhata-102c9.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCOzHZb0nDsb5vNLng0cqdwhGaeC9E8F_w',
    appId: '1:437548364812:ios:202789b9025331521aaa29',
    messagingSenderId: '437548364812',
    projectId: 'sajilokhata-102c9',
    storageBucket: 'sajilokhata-102c9.firebasestorage.app',
    iosBundleId: 'com.example.sajiloKhata',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCOzHZb0nDsb5vNLng0cqdwhGaeC9E8F_w',
    appId: '1:437548364812:ios:202789b9025331521aaa29',
    messagingSenderId: '437548364812',
    projectId: 'sajilokhata-102c9',
    storageBucket: 'sajilokhata-102c9.firebasestorage.app',
    iosBundleId: 'com.example.sajiloKhata',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAV0gawAWIe3-D1eq_xFH06bwIjraNxF88',
    appId: '1:437548364812:web:7b2b4876246341d21aaa29',
    messagingSenderId: '437548364812',
    projectId: 'sajilokhata-102c9',
    authDomain: 'sajilokhata-102c9.firebaseapp.com',
    storageBucket: 'sajilokhata-102c9.firebasestorage.app',
    measurementId: 'G-G7SWYJTH71',
  );
}
